/**
 * G-code parser: file -> ParsedPrint (layers of extrusion segments + metadata).
 *
 * Handles the dialects emitted by OrcaSlicer / AnycubicSlicerNext /
 * PrusaSlicer / Cura: G0/G1/G2/G3, G90/G91, M82/M83, G92, G28, and the `;TAG:`
 * comment blocks.
 */

import { createReadStream } from "node:fs";
import { createInterface } from "node:readline";

/** An extrusion move counts only if it pushes this much filament (mm). */
const MIN_E = 1e-6;
/** Reject segments whose Z is this far from the layer's declared Z. */
const Z_TOL = 0.6;

export interface Seg {
  x0: number;
  y0: number;
  x1: number;
  y1: number;
  z0: number;
  z1: number;
  feat: string;
  width: number;
  obj: string;
  length: number;
  area: number;
}

export interface Layer {
  index: number;
  z: number;
  height: number;
  bottom: number;
  top: number;
  segs: Seg[];
}

export interface ParsedPrint {
  path: string;
  layers: Layer[];
  objects: string[];
  featureCounts: Record<string, number>;
  featureLen: Record<string, number>;
  settings: Record<string, string>;
  settingsSections: Record<string, Record<string, string>>;
  thumbnail: Buffer | null;
  thumbnailSize: [number, number] | null;
  declaredLayers: number | null;
  totalLines: number;
  moveCount: number;
  warnings: string[];
  slicer: string | null;
}

/** Feature names that form the actual part surface. */
export const SHELL_FEATURES = new Set([
  "outer wall",
  "inner wall",
  "top surface",
  "bottom surface",
  "internal solid infill",
  "overhang wall",
  "bridge",
  "internal bridge",
  "custom",
  "skin",
]);

export const SPARSE_FEATURES = new Set([
  "sparse infill",
  "gap infill",
  "ironing",
  "ironing (top)",
]);

export const SUPPORT_FEATURES = new Set([
  "support",
  "support interface",
  "supporting",
]);

const SECTION_TAGS: Record<string, string> = {
  print_settings: "print",
  filament_settings: "filament",
  printer_settings: "printer",
  object_settings: "object",
  custom_settings: "custom",
};

const RE_TYPE = /^\s*;\s*TYPE\s*:\s*(.+?)\s*$/;
const RE_WIDTH = /^\s*;\s*WIDTH\s*:\s*([0-9.eE+-]+)\s*$/;
const RE_Z = /^\s*;\s*Z\s*:\s*([0-9.eE+-]+)\s*$/;
const RE_HEIGHT = /^\s*;\s*HEIGHT\s*:\s*([0-9.eE+-]+)\s*$/;
const RE_OBJ_NAME = /^\s*;\s*printing object\s+(.+?)\s+id:(\d+)\s+copy\s+(\d+)\s*$/;
const RE_OBJ_DEFINE = /EXCLUDE_OBJECT_(?:START|DEFINE)\s+NAME=(\S+)/;
const RE_THUMB_START = /^\s*;\s*thumbnail begin\s+(\d+)x(\d+)\s+(\d+)\s*$/;
const RE_TOTAL_LAYERS = /^\s*;\s*total layer number\s*:\s*(\d+)\s*$/i;
const RE_SLICER = /^\s*;\s*generated by\s+(.+?)\s+on\s+\d{4}-\d{2}-\d{2}/i;
const RE_KV = /^\s*;\s*([^=]+?)\s*=\s*(.*)$/;

/** Interpolate a G2/G3 arc into a list of XY points. */
function arcPoints(
  x0: number,
  y1unused: number,
  y0: number,
  y1: number,
  i: number,
  j: number,
  r: number,
  cw: boolean,
  tol = 0.02
): Array<[number, number]> {
  let cx: number;
  let cy: number;
  if (i === 0 && j === 0 && r !== 0) {
    const dx = y1unused - x0;
    const dy = y1 - y0;
    const d = Math.hypot(dx, dy);
    if (d === 0 || Math.abs(r) < d / 2) return [[y1unused, y1]];
    const h = Math.sqrt(Math.max(r * r - (d / 2) ** 2, 0));
    const sign = (r > 0) !== cw ? 1 : -1;
    cx = x0 + dx / 2 - sign * h * (dy / d);
    cy = y0 + dy / 2 + sign * h * (dx / d);
  } else {
    cx = x0 + i;
    cy = y0 + j;
  }

  const r0 = Math.hypot(x0 - cx, y0 - cy);
  let a0 = Math.atan2(y0 - cy, x0 - cx);
  let a1 = Math.atan2(y1 - cy, y1unused - cx);
  if (cw) {
    while (a1 >= a0) a1 -= 2 * Math.PI;
  } else {
    while (a1 <= a0) a1 += 2 * Math.PI;
  }
  const sweep = a1 - a0;
  if (Math.abs(sweep) < 1e-12) return [[y1unused, y1]];

  const step =
    r0 > tol
      ? 2 * Math.acos(Math.max(-1, Math.min(1, 1 - tol / Math.max(r0, 1e-9))))
      : Math.abs(sweep);
  const n = Math.max(2, Math.ceil(Math.abs(sweep) / Math.max(step, 1e-6)));

  const out: Array<[number, number]> = [];
  for (let k = 1; k <= n; k++) {
    const a = a0 + (sweep * k) / n;
    out.push([cx + r0 * Math.cos(a), cy + r0 * Math.sin(a)]);
  }
  out[out.length - 1] = [y1unused, y1];
  return out;
}

export interface ParseOptions {
  maxLayers?: number;
  onProgress?: (lines: number) => void;
}

export async function parseFile(
  path: string,
  opts: ParseOptions = {}
): Promise<ParsedPrint> {
  const p: ParsedPrint = {
    path,
    layers: [],
    objects: [],
    featureCounts: {},
    featureLen: {},
    settings: {},
    settingsSections: {},
    thumbnail: null,
    thumbnailSize: null,
    declaredLayers: null,
    totalLines: 0,
    moveCount: 0,
    warnings: [],
    slicer: null,
  };

  let x = 0;
  let y = 0;
  let z = 0;
  let eAbs = 0;
  let absXyz = true;
  let absE = false;
  let inLayer = false;
  let inObject = false;
  let obj = "default";
  let feat = "unknown";
  let width = 0;
  let cur: Layer | null = null;
  let section: string | null = null;
  let thumbLines: string[] | null = null;

  const stream = createReadStream(path, { encoding: "utf8" });
  const rl = createInterface({ input: stream, crlfDelay: Infinity });

  const pushSeg = (
    x0: number,
    y0: number,
    x1: number,
    y1: number,
    z0: number,
    z1: number
  ) => {
    const len = Math.hypot(x1 - x0, y1 - y0);
    const w = width || 0.42;
    const s: Seg = { x0, y0, x1, y1, z0, z1, feat, width: w, obj, length: len, area: len * w };
    cur!.segs.push(s);
    p.featureCounts[feat] = (p.featureCounts[feat] ?? 0) + 1;
    p.featureLen[feat] = (p.featureLen[feat] ?? 0) + len;
  };

  for await (const line of rl) {
    p.totalLines++;
    if (!line) continue;

    // ---- thumbnail block (base64) ----
    if (thumbLines !== null) {
      const s = line.trim();
      if (s.startsWith(";")) {
        if (s.includes("thumbnail end")) {
          try {
            p.thumbnail = Buffer.from(thumbLines.join(""), "base64");
          } catch (e) {
            p.warnings.push(`thumbnail decode failed: ${String(e)}`);
          }
          thumbLines = null;
        } else {
          const body = s.replace(/^;+/, "").trim();
          if (body) thumbLines.push(body);
        }
        continue;
      }
      const s2 = s.replace(/;/g, "").trim();
      if (s2) thumbLines.push(s2);
      continue;
    }

    const c = line[0];

    // ---- comments / tags ----
    if (c === ";" || (c === " " && line.trimStart().startsWith(";"))) {
      const s = line.trimStart().replace(/^;+/, "").trim();

      const mt = RE_THUMB_START.exec(line);
      if (mt) {
        thumbLines = [];
        p.thumbnailSize = [parseInt(mt[1], 10), parseInt(mt[2], 10)];
        continue;
      }
      const ms = RE_SLICER.exec(line);
      if (ms) p.slicer = ms[1];

      const mtype = RE_TYPE.exec(line);
      if (mtype) {
        feat = mtype[1];
        continue;
      }
      const mw = RE_WIDTH.exec(line);
      if (mw) {
        width = parseFloat(mw[1]);
        continue;
      }
      const mz = RE_Z.exec(line);
      if (mz && inLayer && cur) {
        cur.z = parseFloat(mz[1]);
        cur.bottom = cur.height ? cur.z - cur.height : cur.z;
        cur.top = cur.z;
        continue;
      }
      const mh = RE_HEIGHT.exec(line);
      if (mh && inLayer && cur) {
        cur.height = parseFloat(mh[1]);
        cur.bottom = cur.z - cur.height;
        cur.top = cur.z;
        continue;
      }
      const ml = RE_TOTAL_LAYERS.exec(line);
      if (ml) {
        p.declaredLayers = parseInt(ml[1], 10);
        continue;
      }
      if (s.startsWith("LAYER_CHANGE")) {
        inLayer = true;
        inObject = false;
        const layer: Layer = {
          index: p.layers.length,
          z,
          height: 0,
          bottom: z,
          top: z,
          segs: [],
        };
        p.layers.push(layer);
        cur = layer;
        if (opts.maxLayers && p.layers.length >= opts.maxLayers) break;
        continue;
      }
      const mo = RE_OBJ_NAME.exec(line);
      if (mo) {
        obj = mo[1];
        if (!p.objects.includes(obj)) p.objects.push(obj);
        inObject = true;
        continue;
      }
      const md = RE_OBJ_DEFINE.exec(line);
      if (md) continue;

      const mk = RE_KV.exec(line);
      if (mk) {
        const key = mk[1].trim();
        const val = mk[2].trim();
        const low = key.toLowerCase();
        if (low in SECTION_TAGS) {
          section = SECTION_TAGS[low];
          p.settingsSections[section] ??= {};
        } else {
          p.settings[key] = val;
        }
      }
      continue;
    }

    if (c !== "G" && c !== "g" && c !== "M" && c !== "m" && c !== "T" && c !== "t") {
      continue;
    }

    // ---- motion / machine commands ----
    const parts = line.split(/\s+/).filter(Boolean);
    if (parts.length === 0) continue;
    const g = parts[0].toUpperCase();

    if (g === "G90") {
      absXyz = true;
      continue;
    }
    if (g === "G91") {
      absXyz = false;
      continue;
    }
    if (g === "M82") {
      absE = true;
      continue;
    }
    if (g === "M83") {
      absE = false;
      continue;
    }
    if (g === "G92") {
      for (const w of parts.slice(1)) {
        const k = w[0].toUpperCase();
        const v = parseFloat(w.slice(1));
        if (!Number.isFinite(v)) continue;
        if (k === "E") eAbs = v;
        else if (k === "X") x = v;
        else if (k === "Y") y = v;
        else if (k === "Z") z = v;
      }
      continue;
    }
    if (g === "G28") {
      x = y = z = 0;
      continue;
    }
    if (g.startsWith("M") || g.startsWith("T")) continue;
    if (g !== "G0" && g !== "G1" && g !== "G00" && g !== "G01" && g !== "G2" && g !== "G02" && g !== "G3" && g !== "G03") {
      continue;
    }

    let nx = x;
    let ny = y;
    let nz = z;
    let ne: number | null = null;
    let iOff = 0;
    let jOff = 0;
    let rOff = 0;
    let hasIJ = false;
    let hasR = false;

    for (const w of parts.slice(1)) {
      const k = w[0].toUpperCase();
      const v = parseFloat(w.slice(1));
      if (!Number.isFinite(v)) continue;
      switch (k) {
        case "X":
          nx = absXyz ? v : x + v;
          break;
        case "Y":
          ny = absXyz ? v : y + v;
          break;
        case "Z":
          nz = absXyz ? v : z + v;
          break;
        case "E":
          ne = v;
          break;
        case "I":
          iOff = v;
          hasIJ = true;
          break;
        case "J":
          jOff = v;
          hasIJ = true;
          break;
        case "R":
          rOff = v;
          hasR = true;
          break;
      }
    }

    let de = 0;
    if (ne !== null) {
      if (absE) {
        de = ne - eAbs;
        eAbs = ne;
      } else {
        de = ne;
      }
    }

    p.moveCount++;

    if (de > MIN_E && cur && inObject && inLayer) {
      const zlo = Math.min(z, nz);
      const zhi = Math.max(z, nz);
      if (Math.abs((zlo + zhi) / 2 - cur.z) <= Z_TOL) {
        if (hasIJ || hasR) {
          const cw = g === "G2" || g === "G02";
          const pts = arcPoints(x, nx, y, ny, iOff, jOff, rOff, cw);
          let px = x;
          let py = y;
          for (const [qx, qy] of pts) {
            pushSeg(px, py, qx, qy, z, nz);
            px = qx;
            py = qy;
          }
        } else if (nx !== x || ny !== y) {
          pushSeg(x, y, nx, ny, z, nz);
        }
      }
    }

    x = nx;
    y = ny;
    z = nz;
  }

  if (p.layers.length === 0) {
    p.warnings.push("no layers found; file may not be sliced gcode");
  }
  if (p.declaredLayers && p.layers.length && p.declaredLayers !== p.layers.length) {
    p.warnings.push(
      `declared layer count ${p.declaredLayers} != parsed ${p.layers.length} (early stop?)`
    );
  }
  return p;
}

/** Bounding box of all extrusion segments: [x0,y0,z0,x1,y1,z1]. */
export function bboxOf(p: ParsedPrint): [number, number, number, number, number, number] {
  let xs0 = Infinity;
  let ys0 = Infinity;
  let zs0 = Infinity;
  let xs1 = -Infinity;
  let ys1 = -Infinity;
  let zs1 = -Infinity;
  for (const layer of p.layers) {
    for (const s of layer.segs) {
      if (s.x0 < xs0) xs0 = s.x0;
      if (s.x1 < xs0) xs0 = s.x1;
      if (s.x0 > xs1) xs1 = s.x0;
      if (s.x1 > xs1) xs1 = s.x1;
      if (s.y0 < ys0) ys0 = s.y0;
      if (s.y1 < ys0) ys0 = s.y1;
      if (s.y0 > ys1) ys1 = s.y0;
      if (s.y1 > ys1) ys1 = s.y1;
      if (s.z0 < zs0) zs0 = s.z0;
      if (s.z1 < zs0) zs0 = s.z1;
      if (s.z0 > zs1) zs1 = s.z0;
      if (s.z1 > zs1) zs1 = s.z1;
    }
  }
  if (xs0 > xs1) return [0, 0, 0, 0, 0, 0];
  return [xs0, ys0, zs0, xs1, ys1, zs1];
}

export function objectsInUse(p: ParsedPrint): string[] {
  const seen = new Set<string>();
  for (const layer of p.layers) for (const s of layer.segs) seen.add(s.obj);
  return [...seen];
}